# Generated by Django 3.1 on 2020-08-19 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='sobrenome')),
                ('cidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=30, null=True, verbose_name='estado')),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_dos_clientes')),
                ('criado_em', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
